before:
  hooks:
    - go mod download
    - go generate ./...
dist: binaries
builds:
- goos:
  - darwin
  - linux
  - windows
  mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goarch:
    - amd64
    - arm64
archives:
  -
    id: "es-gencert-cli"
    builds: ['es-gencert-cli']
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'