name: Build

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Calculate Version
        shell: bash
        run: |
          cd /tmp
          go get github.com/mdomke/git-semver
          cd -
          version=$(~/go/bin/git-semver)
          echo "VERSION=${version}" >> $GITHUB_ENV
      -
        name: Build and Publish
        uses: goreleaser/goreleaser-action@v3.0.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Publish (Dry Run)
        uses: goreleaser/goreleaser-action@v3.0.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --skip-publish --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ github.event_name != 'pull_request' }}
          registry: docker.pkg.github.com
          repository: eventstore/es-gencert-cli/es-gencert-cli
          tag_with_ref: true
          platforms: linux/amd64,linux/arm64
